// <auto-generated />
using System;
using Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ContactsAPI.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20220724212420_moredata")]
    partial class moredata
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Entities.Models.Contact", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("contact");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "Amanzimtoti, Durban",
                            DateOfBirth = new DateTime(1996, 7, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Daniel",
                            LastName = "Bailie",
                            PhoneNumber = "0799693943"
                        },
                        new
                        {
                            Id = 2,
                            Address = "Bloemfontein",
                            DateOfBirth = new DateTime(1999, 1, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Armand",
                            LastName = "Van Den Berg",
                            PhoneNumber = "0799693943"
                        },
                        new
                        {
                            Id = 3,
                            Address = "Western Cape",
                            DateOfBirth = new DateTime(1998, 8, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Andrew",
                            LastName = "Trautmann",
                            PhoneNumber = "0799693943"
                        },
                        new
                        {
                            Id = 4,
                            Address = "Pinetown, Durban",
                            DateOfBirth = new DateTime(1991, 10, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Ashton",
                            LastName = "Naidoo",
                            PhoneNumber = "0799693943"
                        },
                        new
                        {
                            Id = 5,
                            Address = "Western Cape",
                            DateOfBirth = new DateTime(1998, 10, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Iviwe",
                            LastName = "Malotana",
                            PhoneNumber = "0799693943"
                        },
                        new
                        {
                            Id = 6,
                            Address = "Baloni, Gauteng",
                            DateOfBirth = new DateTime(1997, 7, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Miguel",
                            LastName = "Serrao",
                            PhoneNumber = "0799693943"
                        },
                        new
                        {
                            Id = 7,
                            Address = "Amanzimtoti, Durban",
                            DateOfBirth = new DateTime(1996, 8, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Brendon",
                            LastName = "Du Plessis",
                            PhoneNumber = "0799693943"
                        },
                        new
                        {
                            Id = 8,
                            Address = "Kloof, Durban",
                            DateOfBirth = new DateTime(1996, 4, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Shaun",
                            LastName = "Mhlanga",
                            PhoneNumber = "0799693943"
                        },
                        new
                        {
                            Id = 9,
                            Address = "Benoni, Gauteng",
                            DateOfBirth = new DateTime(1995, 11, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Skye",
                            LastName = "Mclennan",
                            PhoneNumber = "0799693943"
                        },
                        new
                        {
                            Id = 10,
                            Address = "Waterfall, Durban",
                            DateOfBirth = new DateTime(1994, 7, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Nathan",
                            LastName = "Geel",
                            PhoneNumber = "0799693943"
                        },
                        new
                        {
                            Id = 11,
                            Address = "Westville, Durban",
                            DateOfBirth = new DateTime(1994, 4, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Justin",
                            LastName = "Pillay",
                            PhoneNumber = "0799693943"
                        },
                        new
                        {
                            Id = 12,
                            Address = "Queensburgh, Durban",
                            DateOfBirth = new DateTime(1998, 7, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Tannah",
                            LastName = "Renou",
                            PhoneNumber = "0799693943"
                        },
                        new
                        {
                            Id = 13,
                            Address = "Pietermaritzburg, Durban",
                            DateOfBirth = new DateTime(1998, 4, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Luke",
                            LastName = "Venter",
                            PhoneNumber = "0799693943"
                        },
                        new
                        {
                            Id = 14,
                            Address = "Western Cape",
                            DateOfBirth = new DateTime(1993, 11, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Jason",
                            LastName = "Smit",
                            PhoneNumber = "0799693943"
                        },
                        new
                        {
                            Id = 15,
                            Address = "Pretoria",
                            DateOfBirth = new DateTime(1996, 8, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Terence",
                            LastName = "Frade",
                            PhoneNumber = "0799693943"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
